# Exercise 4.02: Precision, Recall, and F1 Score Calculation

In this exercise, we will calculate the precision, recall value, and the $F_1$ score of two different classifiers on a simulated dataset.

1.- Import the `numpy` package as `np` using the following code:

In [1]:
import numpy as np

2.- Create a `numpy` array called `real_labels` that contains the values `[True, True, False, True, True]`. This list will represent the true values of the target variable for our simulated dataset. Print its content:

Output:

```
array([ True, True, False, True, True])
```

In [2]:
real_labels = np.array([True, True, False, True, True])
real_labels

array([ True,  True, False,  True,  True])

3.- Create a `numpy` array called `model_1_preds` that contains the values `[True, False, False, False, False]`. This list will represent the predicted values of the first classifier. Print its content.

Output

```
array([ True, False, False, False, False])
```

In [3]:

model_1_preds = np.array([True, False, False, False, False])
model_1_preds

array([ True, False, False, False, False])

4.- Create another `numpy` array `called model_2_preds` that contains the values `[True, True, True, True, True]`. This list will represent the predicted values of the first classifier. Print its content

In [4]:
model_2_preds = np.array([True, True, True, True, True])
model_2_preds

array([ True,  True,  True,  True,  True])

5.- Create a variable called `model_1_tp_cond` that will find the true positives for the first model.

Output:

```
array([ True, False, False, False, False])
```

In [5]:
model_1_tp_cond = (real_labels == True) & (model_1_preds == True)
model_1_tp_cond

array([ True, False, False, False, False])

6.- Create a variable called `model_1_tp` that will get the number of true positives for the first model by summing `model_1_tp_cond`.

Output:

1

There is only 1 true positive case for the first model.

In [6]:
model_1_tp = model_1_tp_cond.sum()
model_1_tp

1

7.- Create a variable called `model_1_fp` that will get the number of false positives for the first model:

Output:

0

There is no false positive for the first model.

In [7]:
model_1_fp = ((real_labels == False) & (model_1_preds == True)).sum()
model_1_fp

0

8.- Create a variable called `model_1_fn` that will get the number of false negatives for the first model:

Output:
3

The first classifier presents 3 false negative cases.

In [9]:
model_1_fn = ((real_labels == True) & (model_1_preds == False)).sum()
model_1_fn

3

9.- Create a variable called `model_1_precision` that will calculate the precision for the first model:

Output:
1.0

The first classifier has a precision score of 1, so it didn't predict any false positives.

In [10]:

model_1_precision = model_1_tp / (model_1_tp + model_1_fp) 
model_1_precision

1.0

10.- Create a variable called `model_1_recall` that will calculate the recall for the first model.

Output:
0.25

The recall score for the first model is only $0.25$, so it is predicting quite a lot of false negatives.

In [11]:
model_1_recall = model_1_tp / (model_1_tp + model_1_fn)
model_1_recall

0.25

11.- Create a variable called `model_1_f1` that will calculate the $F_1$ score for the first model.

Output:
0.4

In [12]:
model_1_f1 = 2 * model_1_precision * model_1_recall / (model_1_precision + model_1_recall)
model_1_f1

0.4

12.- Create a variable called `model_2_tp` that will get the number of true positives for the second model.

Output:
4

In [13]:

model_2_tp = ((real_labels == True) & (model_2_preds == True)).sum()
model_2_tp

4

13.- Create a variable called `model_2_fp` that will get the number of false positives for the second model

Output:
1


There is only one false positive for the second model.

In [14]:
model_2_fp = ((real_labels == False) & (model_2_preds == True)).sum()
model_2_fp

1

14.- Create a variable called `model_2_fn` that will get the number of false negatives for the second model

Output
0

There is no false negative for the second classifier.

In [15]:

model_2_fn = ((real_labels == True) & (model_2_preds == False)).sum()
model_2_fn

0

15.- Create a variable called `model_2_precision` that will calculate precision for the second model:

Output:
0.8

The precision score for the second model is quite high: 0.8. It is not making too many mistakes regarding false positives.

In [16]:
model_2_precision = model_2_tp / (model_2_tp + model_2_fp) 
model_2_precision

0.8

16.- Create a variable called `model_2_recall` that will calculate recall for the second model

Output:
1.0

In terms of recall, the second classifier did a great job and didn't misclassify observations to false negatives.

In [18]:
model_2_recall = model_2_tp / (model_2_tp + model_2_fn)
model_2_recall

1.0

17.- Create a variable called `model_2_f1` that will calculate the $F_1$ score for the second model

Output:
0.888888888888889

The $F_1$ score is quite high for the second model.

In [19]:
model_2_f1 = 2 * model_2_precision * model_2_recall / (model_2_precision + model_2_recall)
model_2_f1

0.888888888888889

In this exercise, we saw how to manually calculate the precision, recall, and $F_1$ score for two different models. The first classifier has excellent precision but bad recall, while the second classifier has excellent recall and quite good precision.